[workspace]
resolver = "2"

members = [
    "databroker-examples",
    "kuksa-rust-sdk",
]

[workspace.dependencies]
kuksa-rust-sdk = { path = "kuksa-rust-sdk" }

# prost has no features
prost = "0.12.6"
# prost-types has no features
prost-types = "0.12.6"
# tokio does not enable features by default
tokio = "1.43.1"
# tokio-stream has no features
tokio-stream = "0.1.8"
tonic = { version = "0.11.0", default-features = false }
tonic-build = { version = "0.8", default-features = false }
